name: Build Executables for Multiple Platforms

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permite ejecuci贸n manual del workflow

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        arch: [x86_64, arm64]  # amd64 y arm64
        exclude:
          - os: windows-latest
            arch: arm64  # Windows solo se compila para x86 (32/64-bit)
        python-version: ["3.8"]

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies (Linux/MacOS)
        if: matrix.os != 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
        shell: bash

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel
          if exist src\requirements.txt ( pip install -r src\requirements.txt )
        shell: cmd

      # Compilaci贸n para Linux con glibc 2.26 usando Docker
      - name: Compile for Linux (glibc 2.26)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          docker run --rm -v $(pwd):/src python:3.8 /bin/bash -c "\
          apt update && \
          apt install -y build-essential glibc-source glibc-doc glibc-2.26 && \
          cd /src/src && python _compile.py"
        shell: bash

      # Compilaci贸n directa para macOS
      - name: Run _compile.py (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          python src/_compile.py
        shell: bash

      # Compilaci贸n directa para Windows
      - name: Run _compile.py (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python src\_compile.py
        shell: cmd

      # Subir los ejecutables generados
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: executable-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/*
