name: Enhancement Request
description: Create an Enhancement Request to help us improve
title: '[ENHANCEMENT]: '
labels:
- enhancement
- public
projects:
- jaimetur/PhotoMigrator
assignees:
- jaimetur
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this feature request!

      '
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What tool version are you running?
    options:
    - v4.6.0 (latest-stable)
    - v4.5.0
    - v4.4.1
    - v4.4.0
    - v4.3.3
    - v4.3.2
    - v4.3.1
    - v4.3.0
    - v4.2.0
    - v4.1.0
    - v4.0.0
    - v3.8.0
    - v3.7.1
    - v3.7.0
    - v3.6.2
    - v3.6.1
    - v3.6.0
    - v3.5.2
    - v3.5.1
    - v3.5.0
    - v3.4.4
    - v3.4.3
    - v3.4.2
    - v3.4.1
    - v3.4.0
    - v3.3.2
    - v3.3.1
    - v3.3.0
    - v3.2.0
    - v3.1.0
    default: 0
  validations:
    required: true
- type: dropdown
  id: feature-affected
  attributes:
    label: Feature Affected
    description: What Feature of the tool will be affected by this Improvement Request?
    options:
    - Global (all features will be affected)
    - Web Interface
    - GUI Interface
    - TUI Interface
    - Logging / Text Messages
    - Documentation
    - Automatic Migration
    - Google Takeout Fixing
    - iCloud Takeout Fixing
    - Google Photos
    - Synology Photos
    - Immich Photos
    - Nextcloud Photos
    - Local Folder Class
    - Album Auto-Renaming
    - Find Duplicates
    - Fix Symbolic Links
    - Docker Running
    - Other
    default: 0
  validations:
    required: true
- type: textarea
  id: improvement-description
  attributes:
    label: Improvement Description
    description: Improvement description
    placeholder: Tell us, with the maximum level of detail, this improvement request
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](/CODE_OF_CONDUCT.md).
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
