name: Feature Request
description: Create a Feature Request to help us improve
title: "[NEW FEATURE]: "
labels: ["feature-request", "public"]
projects: ["jaimetur/PhotoMigrator"]
assignees:
  - jaimetur
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: dropdown
    id: feature-affected
    attributes:
      label: Feature Affected
      description: What Feature of the tool is affected by this Feature Request?
      options:
        - Global (all features will be affected)
        - Logging / Text Messages
        - Documentation
        - Automatic Migration
        - Google Takeout Processing
        - Synology Photos
        - Immich Photos
        - Album Auto-Renaming
        - Find Duplicates
        - Fix Symbolic Links
        - Docker Running
      default: 0
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Tell us, with the maximum level of detail, this feature request
      placeholder: Feature description
      value: "Feature description"
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/jaimetur/PhotoMigrator/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
