name: Feature Request
description: Create a Feature Request to help us improve
title: '[NEW FEATURE]: '
labels:
- feature-request
- public
projects:
- jaimetur/PhotoMigrator
assignees:
- jaimetur
body:
- type: markdown
  attributes:
    value: 'Thanks for taking the time to fill out this feature request!

      '
- type: dropdown
  id: version
  attributes:
    label: Version
    description: What version of our software are you running?
    options:
    - v3.4.1 (latest)
    - v3.4.0 (latest-stable)
    - v3.3.2
    - v3.3.1
    - v3.3.0
    - v3.2.0
    - v3.1.0
    - v3.0.0
    - v2.3.0
    - v2.2.1
    - v2.2.0
    - v2.1.0
    - v2.0.0
    - v1.6.0
    - v1.5.1
    - v1.5.0
    - v1.4.1
    - v1.4.0
    - v1.3.1
    - v1.3.0
    - v1.2.2
    - v1.2.1
    - v1.2.0
    default: 0
  validations:
    required: true
- type: dropdown
  id: feature-affected
  attributes:
    label: Feature Affected
    description: What Feature of the tool is affected by this Feature Request?
    options:
    - Global (all features will be affected)
    - Logging / Text Messages
    - Documentation
    - Automatic Migration
    - Google Takeout Fixing
    - Synology Photos
    - Immich Photos
    - Local Folder Class
    - Album Auto-Renaming
    - Find Duplicates
    - Fix Symbolic Links
    - Docker Running
    - Other
    default: 0
  validations:
    required: true
- type: textarea
  id: feature-description
  attributes:
    label: Feature Description
    description: Tell us, with the maximum level of detail, this feature request
    placeholder: Feature description
    value: Feature description
  validations:
    required: true
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/jaimetur/PhotoMigrator/blob/main/CODE_OF_CONDUCT.md).
    options:
    - label: I agree to follow this project's Code of Conduct
      required: true
