name: 📣 Notify Discord on Release

# This workflow triggers when a new GitHub release is published
on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      # Send a notification to the #releases channel
      - name: Notify in #releases channel
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "username": "GitHub Bot",
                     "embeds": [{
                       "title": "🚀 New Release Published",
                       "description": "**${{ github.repository }}** has published version **${{ github.event.release.tag_name }}**.\n[View release](${{ github.event.release.html_url }})",
                       "color": 3447003
                     }]
                   }' \
               ${{ secrets.DISCORD_WEBHOOK_URL_RELEASES }}

      # Send a notification to the #new_releases channel
      - name: Notify in #new_releases channel
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "username": "GitHub Bot",
                     "embeds": [{
                       "title": "🚀 New Release Published",
                       "description": "Version **${{ github.event.release.tag_name }}** is now available!\n[Details here](${{ github.event.release.html_url }})",
                       "color": 15105570
                     }]
                   }' \
               ${{ secrets.DISCORD_WEBHOOK_URL_NEW_RELEASES }}
