name: Notify Discord on Release

on:
  release:
    types: [published]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                     "username": "GitHub Bot",
                     "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                     "embeds": [{
                       "title": "🚀 Nueva versión publicada",
                       "description": "**${{ github.repository }}** ha publicado la versión **${{ github.event.release.tag_name }}**.\n[Ver release](${{ github.event.release.html_url }})",
                       "color": 5814783
                     }]
                   }' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
